// AUTO-GENERATED by scripts/prepare.mjs from src/script.json — do not edit by hand.
// Scene timing derived from measured edge-tts voiceover (ai-video-studio prepare.py method).
export interface SceneDef { id: string; visualType: string; frEn: number; frZh: number; captionEn: string; captionZh: string; }
export const SCENES: SceneDef[] = [
  { id: "s1", visualType: "hero-real", frEn: 162, frZh: 189, captionEn: "AI keeps getting better. Ever wonder how much of your job it could actually take?", captionZh: "AI 越来越能干，你有没有想过——你这份工作，它到底能替掉多少？" },
  { id: "s2", visualType: "grid-float", frEn: 246, frZh: 261, captionEn: "Instead of guessing, find out. We borrowed MBTI's idea and sorted every career into 16 AI personality types.", captionZh: "与其瞎猜，不如测一测。我们照着 MBTI 的思路，把所有职业分成了 16 种「AI 职业人格」。" },
  { id: "s3", visualType: "axes-anim", frEn: 303, frZh: 347, captionEn: "How? It comes down to four things: can AI learn your work, is there a clear standard for doing it well, who's accountable when it goes wrong, and does it really have to be you?", captionZh: "怎么分？其实就看四件事：你的活儿 AI 学不学得会，做得好不好有没有个准，真出了错担不担得起责，还有——是不是非你不可。" },
  { id: "s4", visualType: "result-real", frEn: 569, frZh: 590, captionEn: "Take me — I came out ESRP, the Pressure Alchemist: I make the calls in the moments you can't afford to get wrong. AI can learn the craft, but when good is fuzzy and a mistake costs everything, the decision still has to be human. So my risk is low — at most thirty percent gets taken, the rest is still mine.", captionZh: "就拿我来说，测出来是 ESRP，高压炼金师——专挑那种错不起的关键时刻拍板。这种判断 AI 学得会，可好坏说不准、错了又赔不起，真要定，还得是人。所以我风险很低，最多三成会被接手，剩下的，都还是我的。" },
  { id: "s5", visualType: "which-pivot", frEn: 131, frZh: 133, captionEn: "So what about you? Of the 16, which one are you?", captionZh: "那你呢？这 16 种里，你是哪一种？" },
  { id: "s6", visualType: "cta", frEn: 276, frZh: 272, captionEn: "Your result in as little as three minutes. You might be harder to replace than you think. Come try it at air dot democra dot ai.", captionZh: "最快 3 分钟就知道结果。说不定，你比自己以为的，更难被取代。来 air democra ai 试试。" },
];
