// AUTO-GENERATED by scripts/prepare.mjs from src/script.json — do not edit by hand.
// Scene timing derived from measured edge-tts voiceover (ai-video-studio prepare.py method).
export interface SceneDef { id: string; visualType: string; frEn: number; frZh: number; captionEn: string; captionZh: string; }
export const SCENES: SceneDef[] = [
  { id: "s1", visualType: "hero-real", frEn: 159, frZh: 175, captionEn: "AI is redrawing which jobs still need a human. Which kind is yours?", captionZh: "AI 正在重新决定，哪些工作还需要人——你的，算哪一种？" },
  { id: "s2", visualType: "grid-float", frEn: 149, frZh: 163, captionEn: "Like MBTI, we sort careers into 16 archetypes.", captionZh: "像 MBTI 一样，我们把职业也分成了 16 种原型。" },
  { id: "s3", visualType: "axes-anim", frEn: 237, frZh: 281, captionEn: "Sorted by four questions: Can AI learn it? Is there a clear standard? Who takes the blame? Does it have to be you?", captionZh: "靠四个问题来分：AI 能不能学会？有没有判断标准？能不能担责？是否必须人来做？" },
  { id: "s4", visualType: "result-real", frEn: 529, frZh: 525, captionEn: "I took it — I'm an ESRP, the Pressure Alchemist: high-stakes, irreversible creative calls where a mistake costs everything. AI can learn the craft, but the judgment is too subjective to hand off. Low risk — only about thirty percent gets taken, the rest stays mine.", captionZh: "我自己测了一下，是 ESRP，高压炼金师——在错了就赔不起的时刻，做不可逆的创造决策。AI 学得会，可好坏太主观，关键时刻还得交给人。低风险，大约只有三成会被接手，剩下都是我的。" },
  { id: "s5", visualType: "which-pivot", frEn: 120, frZh: 149, captionEn: "Which of the 16 are you? You can find out right now.", captionZh: "16 种里，你是哪一种？现在就能测出来。" },
  { id: "s6", visualType: "cta", frEn: 393, frZh: 354, captionEn: "Free, no signup — 16 questions in three minutes for a quick read, 60 in twelve for a precise one. When you're done, send it to someone who should see their own map too. air dot democra dot ai.", captionZh: "免费，不用留邮箱——16 题 3 分钟更快，60 题 12 分钟更准。测完，发给那个也该看看自己坐标的人。air democra ai。" },
];
