// Audio build step — mirrors ai-video-studio/scripts/prepare.py.
// Reads src/script.json (the canonical script), synthesizes each scene's narration
// per language via edge-tts (female voices), measures real durations with ffprobe,
// writes public/audio/<lang>/scene-NN.mp3 and emits src/scene-data.ts (timed scenes).
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const script = JSON.parse(fs.readFileSync(path.join(ROOT, 'src/script.json'), 'utf8'));
const FPS = script.fps || 30;
const PITCH = '+0Hz';
const LEAD = 10; // VO lead-in frames
const TAIL = 14; // breathing room after VO
const LANGS = ['en', 'zh'];

const ffdur = (p) =>
  parseFloat(execFileSync('ffprobe', ['-v', 'error', '-show_entries', 'format=duration', '-of', 'default=nk=1:nw=1', p]).toString().trim());

const meta = {};
for (const lang of LANGS) {
  const { voice, rate } = script.audio[lang];
  const dir = path.join(ROOT, 'public/audio', lang);
  fs.mkdirSync(dir, { recursive: true });
  meta[lang] = [];
  script.scenes.forEach((sc, i) => {
    const n = String(i + 1).padStart(2, '0');
    const file = path.join(dir, `scene-${n}.mp3`);
    const text = lang === 'en' ? sc.narrationEn : sc.narrationZh;
    execFileSync('edge-tts', ['--voice', voice, '--rate', rate, '--pitch', PITCH, '--text', text, '--write-media', file], { stdio: 'ignore' });
    const d = ffdur(file);
    meta[lang].push(d);
    console.log(`[${lang}] scene ${i + 1} [${sc.visualType.padStart(11)}] ${d.toFixed(2)}s`);
  });
}

const frames = (d) => Math.round(d * FPS) + LEAD + TAIL;
const esc = (s) => JSON.stringify(s);
const rows = script.scenes.map((sc, i) =>
  `  { id: ${esc(sc.id)}, visualType: ${esc(sc.visualType)}, frEn: ${frames(meta.en[i])}, frZh: ${frames(meta.zh[i])}, captionEn: ${esc(sc.captionEn)}, captionZh: ${esc(sc.captionZh)} },`
);
const ts = `// AUTO-GENERATED by scripts/prepare.mjs from src/script.json — do not edit by hand.
// Scene timing derived from measured edge-tts voiceover (ai-video-studio prepare.py method).
export interface SceneDef { id: string; visualType: string; frEn: number; frZh: number; captionEn: string; captionZh: string; }
export const SCENES: SceneDef[] = [
${rows.join('\n')}
];
`;
fs.writeFileSync(path.join(ROOT, 'src/scene-data.ts'), ts);

const tot = (lang) => meta[lang].reduce((a, d) => a + frames(d), 0) / FPS;
console.log(`\nEN total ≈ ${tot('en').toFixed(1)}s · ZH total ≈ ${tot('zh').toFixed(1)}s  (LEAD ${LEAD} + TAIL ${TAIL} frames/scene)`);
console.log('written → src/scene-data.ts + public/audio/{en,zh}/scene-NN.mp3');
