/**
 * AUTO-GENERATED by scripts/gen-occupations.mjs — do not edit by hand.
 * 160 BLS occupations (from PROFILE_CAREERS) anchored at hand-authored
 * REALISTIC 16-answer vectors. Each `archetype` is COMPUTED from its vector via
 * the production calculator, so the nearest-neighbour guesser is self-consistent.
 */
import type { OccupationPattern } from './occupation_inference';

export interface AnchoredOccupation extends OccupationPattern {
  archetype: string;
}

export const BLS_OCCUPATIONS: AnchoredOccupation[] = [
  {
    "id": "customer-service-representatives",
    "title": {
      "en": "Customer Service Representatives",
      "zh": "客服专员"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      2,
      2,
      4,
      3,
      3,
      2,
      2,
      4,
      4,
      2,
      3,
      4,
      1,
      2
    ]
  },
  {
    "id": "office-clerks-general",
    "title": {
      "en": "Office Clerks, General",
      "zh": "普通办公室文员"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      2,
      1,
      5,
      5,
      2,
      1,
      2,
      4,
      5,
      2,
      2,
      5,
      1,
      2
    ]
  },
  {
    "id": "secretaries-and-administrative-assistant",
    "title": {
      "en": "Secretaries and Administrative Assistants",
      "zh": "行政助理"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      2,
      2,
      4,
      4,
      2,
      2,
      2,
      4,
      4,
      2,
      2,
      5,
      2,
      2
    ]
  },
  {
    "id": "receptionists-and-information-clerks",
    "title": {
      "en": "Receptionists and Information Clerks",
      "zh": "前台接待员"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      4,
      4,
      2,
      1,
      4,
      4,
      2,
      1,
      2,
      4,
      4,
      2,
      3,
      5,
      3,
      2
    ]
  },
  {
    "id": "medical-secretaries-and-administrative-a",
    "title": {
      "en": "Medical Secretaries and Administrative Assistants",
      "zh": "医疗行政助理"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      2,
      2,
      5,
      4,
      2,
      1,
      3,
      4,
      3,
      2,
      2,
      4,
      2,
      2
    ]
  },
  {
    "id": "bookkeeping-accounting-and-auditing-cler",
    "title": {
      "en": "Bookkeeping, Accounting, and Auditing Clerks",
      "zh": "会计记账员"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      5,
      2,
      1,
      5,
      5,
      1,
      1,
      3,
      3,
      4,
      2,
      2,
      5,
      1,
      2
    ]
  },
  {
    "id": "sales-representatives-of-services",
    "title": {
      "en": "Sales Representatives of Services",
      "zh": "服务业销售代表"
    },
    "socGroup": 0,
    "archetype": "EOFH",
    "answers": [
      4,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      2,
      4,
      4,
      3,
      4,
      3,
      3,
      4
    ]
  },
  {
    "id": "first-line-supervisors-of-retail-sales-w",
    "title": {
      "en": "First-Line Supervisors of Retail Sales Workers",
      "zh": "零售一线主管"
    },
    "socGroup": 0,
    "archetype": "EOFH",
    "answers": [
      4,
      3,
      4,
      3,
      4,
      3,
      4,
      3,
      2,
      4,
      4,
      3,
      4,
      3,
      4,
      3
    ]
  },
  {
    "id": "counter-and-rental-clerks",
    "title": {
      "en": "Counter and Rental Clerks",
      "zh": "柜台与租赁服务员"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      4,
      4,
      2,
      2,
      4,
      4,
      2,
      2,
      2,
      4,
      4,
      2,
      3,
      4,
      4,
      3
    ]
  },
  {
    "id": "retail-salespersons",
    "title": {
      "en": "Retail Salespersons",
      "zh": "零售销售员"
    },
    "socGroup": 0,
    "archetype": "EOFH",
    "answers": [
      3,
      4,
      2,
      2,
      3,
      4,
      2,
      2,
      2,
      4,
      4,
      2,
      4,
      4,
      4,
      3
    ]
  },
  {
    "id": "insurance-sales-agents",
    "title": {
      "en": "Insurance Sales Agents",
      "zh": "保险销售代理"
    },
    "socGroup": 0,
    "archetype": "EOFH",
    "answers": [
      4,
      3,
      3,
      3,
      4,
      3,
      3,
      2,
      3,
      4,
      4,
      3,
      4,
      3,
      3,
      4
    ]
  },
  {
    "id": "cashiers",
    "title": {
      "en": "Cashiers",
      "zh": "收银员"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      3,
      4,
      2,
      1,
      4,
      5,
      2,
      1,
      2,
      4,
      4,
      2,
      3,
      5,
      4,
      2
    ]
  },
  {
    "id": "market-research-analysts-and-marketing-s",
    "title": {
      "en": "Market Research Analysts and Marketing Specialists",
      "zh": "市场研究分析师"
    },
    "socGroup": 0,
    "archetype": "ESFP",
    "answers": [
      5,
      3,
      3,
      3,
      3,
      2,
      4,
      4,
      3,
      4,
      4,
      3,
      3,
      3,
      2,
      3
    ]
  },
  {
    "id": "human-resources-specialists",
    "title": {
      "en": "Human Resources Specialists",
      "zh": "人力资源专员"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      4,
      3,
      2,
      3
    ]
  },
  {
    "id": "business-operations-specialists",
    "title": {
      "en": "Business Operations Specialists",
      "zh": "业务运营专员"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      3,
      3,
      4,
      4,
      3,
      2,
      3,
      3,
      3,
      3,
      3,
      3,
      1,
      3
    ]
  },
  {
    "id": "management-analysts",
    "title": {
      "en": "Management Analysts",
      "zh": "管理顾问"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      3,
      3,
      5,
      3,
      3,
      2,
      3,
      4,
      4,
      3,
      3,
      3,
      1,
      2
    ]
  },
  {
    "id": "project-management-specialists",
    "title": {
      "en": "Project Management Specialists",
      "zh": "项目管理专员"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      3,
      4,
      3,
      4,
      3,
      4,
      3,
      3,
      4,
      4,
      3,
      4,
      3,
      2,
      3
    ]
  },
  {
    "id": "accountants-and-auditors",
    "title": {
      "en": "Accountants and Auditors",
      "zh": "会计师与审计师"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      5,
      5,
      3,
      2,
      5,
      4,
      2,
      2,
      4,
      3,
      2,
      4,
      3,
      3,
      1,
      3
    ]
  },
  {
    "id": "first-line-supervisors-of-production-wor",
    "title": {
      "en": "First-Line Supervisors of Production Workers",
      "zh": "生产一线主管"
    },
    "socGroup": 0,
    "archetype": "EORH",
    "answers": [
      3,
      4,
      3,
      2,
      5,
      4,
      3,
      2,
      4,
      2,
      3,
      3,
      3,
      3,
      5,
      2
    ]
  },
  {
    "id": "inspectors-testers-sorters-samplers-and-",
    "title": {
      "en": "Inspectors, Testers, Sorters, Samplers, and Weighers",
      "zh": "质量检验员"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      3,
      4,
      3,
      2,
      5,
      5,
      2,
      2,
      4,
      2,
      3,
      3,
      2,
      4,
      5,
      2
    ]
  },
  {
    "id": "packaging-and-filling-machine-operators",
    "title": {
      "en": "Packaging and Filling Machine Operators",
      "zh": "包装机操作员"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      3,
      4,
      2,
      1,
      5,
      5,
      2,
      1,
      3,
      2,
      4,
      2,
      2,
      5,
      5,
      2
    ]
  },
  {
    "id": "welders-cutters-solderers-and-brazers",
    "title": {
      "en": "Welders, Cutters, Solderers, and Brazers",
      "zh": "焊接工"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      2,
      4,
      3,
      2,
      5,
      4,
      2,
      2,
      4,
      2,
      3,
      3,
      2,
      4,
      5,
      2
    ]
  },
  {
    "id": "machinists",
    "title": {
      "en": "Machinists",
      "zh": "机械操作工"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      3,
      4,
      3,
      2,
      5,
      4,
      2,
      2,
      4,
      2,
      3,
      3,
      2,
      4,
      5,
      2
    ]
  },
  {
    "id": "bakers",
    "title": {
      "en": "Bakers",
      "zh": "烘焙师"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      2,
      4,
      3,
      2,
      4,
      4,
      2,
      3,
      3,
      3,
      4,
      2,
      2,
      4,
      5,
      3
    ]
  },
  {
    "id": "health-specialties-teachers-postsecondar",
    "title": {
      "en": "Health Specialties Teachers, Postsecondary",
      "zh": "医学类高校教师"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      4,
      3,
      4,
      4,
      2,
      2,
      4,
      4,
      3,
      3,
      3,
      4,
      4,
      2,
      3,
      4
    ]
  },
  {
    "id": "middle-school-teachers",
    "title": {
      "en": "Middle School Teachers",
      "zh": "初中教师"
    },
    "socGroup": 0,
    "archetype": "ESRH",
    "answers": [
      4,
      4,
      3,
      3,
      2,
      2,
      4,
      3,
      3,
      3,
      3,
      4,
      4,
      3,
      4,
      4
    ]
  },
  {
    "id": "secondary-school-teachers",
    "title": {
      "en": "Secondary School Teachers",
      "zh": "高中教师"
    },
    "socGroup": 0,
    "archetype": "ESRH",
    "answers": [
      4,
      4,
      3,
      3,
      2,
      2,
      4,
      3,
      3,
      3,
      3,
      4,
      4,
      3,
      4,
      4
    ]
  },
  {
    "id": "elementary-school-teachers",
    "title": {
      "en": "Elementary School Teachers",
      "zh": "小学教师"
    },
    "socGroup": 0,
    "archetype": "ESRH",
    "answers": [
      3,
      4,
      4,
      3,
      2,
      2,
      4,
      3,
      3,
      3,
      3,
      4,
      4,
      3,
      4,
      4
    ]
  },
  {
    "id": "self-enrichment-teachers",
    "title": {
      "en": "Self-Enrichment Teachers",
      "zh": "兴趣班教师"
    },
    "socGroup": 0,
    "archetype": "ESFH",
    "answers": [
      4,
      3,
      4,
      3,
      2,
      2,
      4,
      4,
      2,
      4,
      4,
      4,
      4,
      3,
      4,
      4
    ]
  },
  {
    "id": "preschool-teachers",
    "title": {
      "en": "Preschool Teachers",
      "zh": "幼儿园教师"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      2,
      3,
      4,
      3,
      1,
      2,
      4,
      3,
      3,
      3,
      3,
      4,
      4,
      3,
      5,
      4
    ]
  },
  {
    "id": "software-developers",
    "title": {
      "en": "Software Developers",
      "zh": "软件开发工程师"
    },
    "socGroup": 0,
    "archetype": "ESFP",
    "answers": [
      5,
      4,
      4,
      4,
      3,
      2,
      4,
      3,
      3,
      4,
      4,
      2,
      2,
      4,
      1,
      2
    ]
  },
  {
    "id": "software-quality-assurance-analysts-and-",
    "title": {
      "en": "Software Quality Assurance Analysts and Testers",
      "zh": "软件测试工程师"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      3,
      3,
      4,
      3,
      4,
      2,
      3,
      4,
      4,
      2,
      2,
      4,
      1,
      2
    ]
  },
  {
    "id": "computer-user-support-specialists",
    "title": {
      "en": "Computer User Support Specialists",
      "zh": "计算机用户支持专员"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      2,
      2,
      4,
      4,
      3,
      2,
      2,
      4,
      4,
      2,
      3,
      4,
      2,
      2
    ]
  },
  {
    "id": "data-scientists",
    "title": {
      "en": "Data Scientists",
      "zh": "数据科学家"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      3,
      3,
      4,
      3,
      4,
      2,
      3,
      4,
      4,
      2,
      2,
      4,
      1,
      2
    ]
  },
  {
    "id": "computer-systems-analysts",
    "title": {
      "en": "Computer Systems Analysts",
      "zh": "计算机系统分析师"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      3,
      3,
      4,
      3,
      4,
      3,
      3,
      4,
      4,
      2,
      3,
      4,
      1,
      2
    ]
  },
  {
    "id": "network-and-computer-systems-administrat",
    "title": {
      "en": "Network and Computer Systems Administrators",
      "zh": "网络与系统管理员"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      3,
      3,
      4,
      4,
      3,
      2,
      3,
      4,
      4,
      2,
      2,
      4,
      2,
      2
    ]
  },
  {
    "id": "administrative-law-judges",
    "title": {
      "en": "Administrative Law Judges",
      "zh": "行政法法官"
    },
    "socGroup": 0,
    "archetype": "EORH",
    "answers": [
      5,
      4,
      4,
      3,
      3,
      3,
      3,
      3,
      4,
      2,
      2,
      4,
      3,
      3,
      3,
      4
    ]
  },
  {
    "id": "arbitrators-mediators-and-conciliators",
    "title": {
      "en": "Arbitrators, Mediators, and Conciliators",
      "zh": "仲裁员与调解员"
    },
    "socGroup": 0,
    "archetype": "ESRH",
    "answers": [
      4,
      3,
      4,
      3,
      2,
      2,
      4,
      4,
      3,
      3,
      3,
      4,
      5,
      2,
      3,
      5
    ]
  },
  {
    "id": "judicial-law-clerks",
    "title": {
      "en": "Judicial Law Clerks",
      "zh": "司法助理"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      5,
      4,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      4,
      3,
      3,
      2,
      3
    ]
  },
  {
    "id": "judges-magistrate-judges-and-magistrates",
    "title": {
      "en": "Judges, Magistrate Judges, and Magistrates",
      "zh": "法官与治安法官"
    },
    "socGroup": 0,
    "archetype": "EORH",
    "answers": [
      5,
      4,
      4,
      3,
      3,
      3,
      3,
      3,
      4,
      2,
      2,
      5,
      4,
      2,
      3,
      5
    ]
  },
  {
    "id": "paralegals-and-legal-assistants",
    "title": {
      "en": "Paralegals and Legal Assistants",
      "zh": "律师助理"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      3,
      2,
      4,
      4,
      3,
      2,
      3,
      3,
      3,
      3,
      2,
      4,
      2,
      3
    ]
  },
  {
    "id": "lawyers",
    "title": {
      "en": "Lawyers",
      "zh": "律师"
    },
    "socGroup": 0,
    "archetype": "ESRH",
    "answers": [
      5,
      4,
      4,
      4,
      3,
      2,
      4,
      3,
      4,
      2,
      2,
      4,
      4,
      2,
      3,
      4
    ]
  },
  {
    "id": "electrical-engineers",
    "title": {
      "en": "Electrical Engineers",
      "zh": "电气工程师"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      5,
      4,
      4,
      3,
      4,
      3,
      3,
      3,
      4,
      3,
      3,
      3,
      2,
      3,
      3,
      3
    ]
  },
  {
    "id": "architects-except-landscape-and-naval",
    "title": {
      "en": "Architects, Except Landscape and Naval",
      "zh": "建筑师"
    },
    "socGroup": 0,
    "archetype": "ESRP",
    "answers": [
      5,
      3,
      4,
      4,
      3,
      2,
      4,
      5,
      4,
      3,
      3,
      3,
      3,
      3,
      3,
      3
    ]
  },
  {
    "id": "mechanical-engineers",
    "title": {
      "en": "Mechanical Engineers",
      "zh": "机械工程师"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      5,
      4,
      4,
      3,
      4,
      3,
      3,
      3,
      4,
      3,
      3,
      3,
      2,
      3,
      3,
      3
    ]
  },
  {
    "id": "civil-engineers",
    "title": {
      "en": "Civil Engineers",
      "zh": "土木工程师"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      5,
      4,
      4,
      3,
      4,
      3,
      3,
      3,
      4,
      2,
      3,
      4,
      3,
      3,
      3,
      3
    ]
  },
  {
    "id": "industrial-engineers",
    "title": {
      "en": "Industrial Engineers",
      "zh": "工业工程师"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      4,
      3,
      4,
      3,
      3,
      3,
      3,
      3,
      4,
      3,
      3,
      3,
      3,
      3
    ]
  },
  {
    "id": "medical-scientists-except-epidemiologist",
    "title": {
      "en": "Medical Scientists, Except Epidemiologists",
      "zh": "医学研究员"
    },
    "socGroup": 0,
    "archetype": "TSFP",
    "answers": [
      5,
      3,
      4,
      5,
      4,
      2,
      4,
      3,
      4,
      4,
      3,
      3,
      3,
      2,
      2,
      3
    ]
  },
  {
    "id": "amusement-and-recreation-attendants",
    "title": {
      "en": "Amusement and Recreation Attendants",
      "zh": "娱乐休闲服务员"
    },
    "socGroup": 0,
    "archetype": "EOFH",
    "answers": [
      2,
      4,
      3,
      2,
      3,
      3,
      3,
      3,
      2,
      4,
      4,
      3,
      3,
      4,
      5,
      3
    ]
  },
  {
    "id": "hairdressers-hairstylists-and-cosmetolog",
    "title": {
      "en": "Hairdressers, Hairstylists, and Cosmetologists",
      "zh": "发型师与美容师"
    },
    "socGroup": 0,
    "archetype": "TSFH",
    "answers": [
      1,
      3,
      4,
      2,
      3,
      3,
      3,
      4,
      2,
      4,
      4,
      2,
      5,
      3,
      5,
      4
    ]
  },
  {
    "id": "manicurists-and-pedicurists",
    "title": {
      "en": "Manicurists and Pedicurists",
      "zh": "美甲师"
    },
    "socGroup": 0,
    "archetype": "TOFH",
    "answers": [
      1,
      3,
      4,
      2,
      3,
      3,
      3,
      3,
      2,
      4,
      4,
      2,
      5,
      3,
      5,
      4
    ]
  },
  {
    "id": "exercise-trainers-and-group-fitness-inst",
    "title": {
      "en": "Exercise Trainers and Group Fitness Instructors",
      "zh": "健身教练"
    },
    "socGroup": 0,
    "archetype": "TSFH",
    "answers": [
      2,
      3,
      4,
      3,
      3,
      2,
      3,
      3,
      2,
      4,
      4,
      3,
      4,
      3,
      5,
      4
    ]
  },
  {
    "id": "childcare-workers",
    "title": {
      "en": "Childcare Workers",
      "zh": "托育工作者"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      2,
      3,
      4,
      3,
      2,
      3,
      3,
      3,
      4,
      3,
      3,
      4,
      4,
      3,
      5,
      4
    ]
  },
  {
    "id": "animal-caretakers",
    "title": {
      "en": "Animal Caretakers",
      "zh": "动物护理员"
    },
    "socGroup": 0,
    "archetype": "TOFH",
    "answers": [
      2,
      3,
      4,
      3,
      3,
      3,
      3,
      3,
      3,
      4,
      4,
      3,
      3,
      4,
      5,
      3
    ]
  },
  {
    "id": "laborers-and-freight-stock-and-material-",
    "title": {
      "en": "Laborers and Freight, Stock, and Material Movers",
      "zh": "仓库搬运工"
    },
    "socGroup": 0,
    "archetype": "TOFP",
    "answers": [
      1,
      3,
      3,
      2,
      4,
      4,
      2,
      1,
      3,
      4,
      4,
      2,
      2,
      5,
      5,
      2
    ]
  },
  {
    "id": "heavy-and-tractor-trailer-truck-drivers",
    "title": {
      "en": "Heavy and Tractor-Trailer Truck Drivers",
      "zh": "重型卡车司机"
    },
    "socGroup": 0,
    "archetype": "TOFP",
    "answers": [
      2,
      3,
      4,
      2,
      4,
      4,
      2,
      1,
      3,
      3,
      4,
      3,
      2,
      4,
      5,
      2
    ]
  },
  {
    "id": "stockers-and-order-fillers",
    "title": {
      "en": "Stockers and Order Fillers",
      "zh": "理货员"
    },
    "socGroup": 0,
    "archetype": "TOFP",
    "answers": [
      1,
      3,
      3,
      2,
      4,
      5,
      2,
      1,
      2,
      4,
      4,
      2,
      2,
      5,
      5,
      2
    ]
  },
  {
    "id": "janitors-and-cleaners",
    "title": {
      "en": "Janitors and Cleaners",
      "zh": "清洁工"
    },
    "socGroup": 0,
    "archetype": "TOFP",
    "answers": [
      1,
      3,
      3,
      2,
      4,
      4,
      2,
      2,
      2,
      4,
      4,
      2,
      2,
      5,
      5,
      2
    ]
  },
  {
    "id": "maintenance-and-repair-workers-general",
    "title": {
      "en": "Maintenance and Repair Workers, General",
      "zh": "综合维修工人"
    },
    "socGroup": 0,
    "archetype": "TOFP",
    "answers": [
      2,
      3,
      4,
      2,
      4,
      4,
      2,
      2,
      3,
      4,
      4,
      2,
      3,
      4,
      5,
      2
    ]
  },
  {
    "id": "landscaping-and-groundskeeping-workers",
    "title": {
      "en": "Landscaping and Groundskeeping Workers",
      "zh": "园林绿化工"
    },
    "socGroup": 0,
    "archetype": "TOFP",
    "answers": [
      1,
      3,
      3,
      2,
      4,
      4,
      2,
      2,
      2,
      4,
      4,
      2,
      2,
      5,
      5,
      2
    ]
  },
  {
    "id": "nurse-practitioners",
    "title": {
      "en": "Nurse Practitioners",
      "zh": "执业护士"
    },
    "socGroup": 0,
    "archetype": "EORH",
    "answers": [
      3,
      4,
      4,
      3,
      4,
      3,
      3,
      2,
      5,
      1,
      2,
      5,
      3,
      2,
      5,
      4
    ]
  },
  {
    "id": "medical-assistants",
    "title": {
      "en": "Medical Assistants",
      "zh": "医疗助理"
    },
    "socGroup": 0,
    "archetype": "TORH",
    "answers": [
      2,
      3,
      4,
      2,
      4,
      4,
      3,
      2,
      4,
      3,
      3,
      4,
      2,
      3,
      5,
      3
    ]
  },
  {
    "id": "registered-nurses",
    "title": {
      "en": "Registered Nurses",
      "zh": "注册护士"
    },
    "socGroup": 0,
    "archetype": "TORH",
    "answers": [
      2,
      4,
      4,
      3,
      4,
      3,
      3,
      2,
      5,
      2,
      2,
      5,
      3,
      3,
      5,
      4
    ]
  },
  {
    "id": "pharmacy-technicians",
    "title": {
      "en": "Pharmacy Technicians",
      "zh": "药房技术员"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      3,
      4,
      4,
      2,
      5,
      5,
      2,
      1,
      5,
      2,
      2,
      5,
      2,
      3,
      4,
      3
    ]
  },
  {
    "id": "licensed-practical-and-licensed-vocation",
    "title": {
      "en": "Licensed Practical and Licensed Vocational Nurses",
      "zh": "执照实习护士"
    },
    "socGroup": 0,
    "archetype": "TORH",
    "answers": [
      2,
      3,
      4,
      2,
      4,
      4,
      2,
      2,
      5,
      2,
      2,
      4,
      2,
      3,
      5,
      3
    ]
  },
  {
    "id": "nursing-assistants",
    "title": {
      "en": "Nursing Assistants",
      "zh": "护理助理"
    },
    "socGroup": 0,
    "archetype": "TORH",
    "answers": [
      2,
      3,
      4,
      2,
      3,
      4,
      3,
      2,
      4,
      3,
      3,
      4,
      2,
      3,
      5,
      3
    ]
  },
  {
    "id": "construction-laborers",
    "title": {
      "en": "Construction Laborers",
      "zh": "建筑工人"
    },
    "socGroup": 0,
    "archetype": "TORP",
    "answers": [
      1,
      3,
      4,
      2,
      4,
      4,
      2,
      2,
      4,
      3,
      3,
      3,
      2,
      4,
      5,
      2
    ]
  },
  {
    "id": "first-line-supervisors-of-construction-t",
    "title": {
      "en": "First-Line Supervisors of Construction Trades",
      "zh": "建筑施工主管"
    },
    "socGroup": 0,
    "archetype": "TORP",
    "answers": [
      2,
      3,
      4,
      3,
      4,
      3,
      3,
      2,
      4,
      3,
      3,
      3,
      2,
      4,
      5,
      2
    ]
  },
  {
    "id": "plumbers-pipefitters-and-steamfitters",
    "title": {
      "en": "Plumbers, Pipefitters, and Steamfitters",
      "zh": "管道工"
    },
    "socGroup": 0,
    "archetype": "TORP",
    "answers": [
      1,
      3,
      4,
      3,
      4,
      4,
      2,
      2,
      4,
      3,
      3,
      3,
      2,
      4,
      5,
      2
    ]
  },
  {
    "id": "electricians",
    "title": {
      "en": "Electricians",
      "zh": "电工"
    },
    "socGroup": 0,
    "archetype": "TORP",
    "answers": [
      1,
      3,
      4,
      3,
      4,
      4,
      2,
      2,
      4,
      3,
      2,
      4,
      2,
      4,
      5,
      2
    ]
  },
  {
    "id": "carpenters",
    "title": {
      "en": "Carpenters",
      "zh": "木工"
    },
    "socGroup": 0,
    "archetype": "TORP",
    "answers": [
      1,
      3,
      4,
      3,
      4,
      4,
      2,
      3,
      4,
      3,
      3,
      3,
      2,
      4,
      5,
      2
    ]
  },
  {
    "id": "operating-engineers-and-other-constructi",
    "title": {
      "en": "Operating Engineers and Other Construction Equipment Operators",
      "zh": "工程机械操作员"
    },
    "socGroup": 0,
    "archetype": "TORP",
    "answers": [
      2,
      3,
      4,
      2,
      4,
      4,
      2,
      2,
      4,
      3,
      3,
      3,
      2,
      4,
      5,
      2
    ]
  },
  {
    "id": "public-relations-specialists",
    "title": {
      "en": "Public Relations Specialists",
      "zh": "公关专员"
    },
    "socGroup": 0,
    "archetype": "ESRH",
    "answers": [
      5,
      3,
      4,
      4,
      3,
      2,
      4,
      4,
      3,
      3,
      3,
      4,
      4,
      3,
      2,
      4
    ]
  },
  {
    "id": "editors",
    "title": {
      "en": "Editors",
      "zh": "编辑"
    },
    "socGroup": 0,
    "archetype": "TSFP",
    "answers": [
      5,
      3,
      5,
      4,
      2,
      2,
      4,
      5,
      2,
      4,
      4,
      3,
      3,
      3,
      1,
      4
    ]
  },
  {
    "id": "interpreters-and-translators",
    "title": {
      "en": "Interpreters and Translators",
      "zh": "翻译员"
    },
    "socGroup": 0,
    "archetype": "ESFP",
    "answers": [
      5,
      3,
      4,
      3,
      3,
      3,
      3,
      4,
      3,
      3,
      3,
      3,
      3,
      3,
      2,
      4
    ]
  },
  {
    "id": "graphic-designers",
    "title": {
      "en": "Graphic Designers",
      "zh": "平面设计师"
    },
    "socGroup": 0,
    "archetype": "TSFP",
    "answers": [
      5,
      2,
      4,
      4,
      2,
      2,
      4,
      5,
      2,
      5,
      4,
      3,
      3,
      3,
      1,
      3
    ]
  },
  {
    "id": "producers-and-directors",
    "title": {
      "en": "Producers and Directors",
      "zh": "制片人与导演"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      4,
      2,
      5,
      4,
      2,
      2,
      4,
      5,
      3,
      3,
      3,
      4,
      5,
      2,
      3,
      5
    ]
  },
  {
    "id": "interior-designers",
    "title": {
      "en": "Interior Designers",
      "zh": "室内设计师"
    },
    "socGroup": 0,
    "archetype": "TSFH",
    "answers": [
      4,
      2,
      4,
      4,
      2,
      2,
      4,
      5,
      3,
      4,
      4,
      3,
      4,
      3,
      3,
      4
    ]
  },
  {
    "id": "first-line-supervisors-of-food-preparati",
    "title": {
      "en": "First-Line Supervisors of Food Preparation and Serving Workers",
      "zh": "餐饮一线主管"
    },
    "socGroup": 0,
    "archetype": "TOFH",
    "answers": [
      2,
      3,
      4,
      3,
      3,
      3,
      3,
      3,
      2,
      4,
      4,
      3,
      3,
      3,
      5,
      3
    ]
  },
  {
    "id": "cooks-restaurant",
    "title": {
      "en": "Cooks, Restaurant",
      "zh": "餐厅厨师"
    },
    "socGroup": 0,
    "archetype": "TSFP",
    "answers": [
      1,
      3,
      5,
      3,
      2,
      2,
      3,
      5,
      2,
      4,
      4,
      3,
      2,
      4,
      5,
      3
    ]
  },
  {
    "id": "fast-food-and-counter-workers",
    "title": {
      "en": "Fast Food and Counter Workers",
      "zh": "快餐服务员"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      2,
      4,
      2,
      2,
      3,
      4,
      2,
      2,
      2,
      4,
      4,
      2,
      2,
      5,
      5,
      2
    ]
  },
  {
    "id": "waiters-and-waitresses",
    "title": {
      "en": "Waiters and Waitresses",
      "zh": "餐厅服务员"
    },
    "socGroup": 0,
    "archetype": "EOFH",
    "answers": [
      2,
      4,
      3,
      2,
      3,
      3,
      3,
      2,
      2,
      4,
      4,
      2,
      3,
      4,
      5,
      3
    ]
  },
  {
    "id": "bartenders",
    "title": {
      "en": "Bartenders",
      "zh": "调酒师"
    },
    "socGroup": 0,
    "archetype": "TSFH",
    "answers": [
      2,
      3,
      4,
      3,
      2,
      2,
      3,
      4,
      2,
      4,
      4,
      3,
      4,
      3,
      5,
      4
    ]
  },
  {
    "id": "food-preparation-workers",
    "title": {
      "en": "Food Preparation Workers",
      "zh": "食品准备工人"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      1,
      4,
      3,
      2,
      3,
      4,
      2,
      2,
      2,
      4,
      4,
      2,
      2,
      5,
      5,
      2
    ]
  },
  {
    "id": "computer-and-information-systems-manager",
    "title": {
      "en": "Computer and Information Systems Managers",
      "zh": "信息技术经理"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      5,
      3,
      5,
      4,
      3,
      3,
      4,
      3,
      4,
      3,
      3,
      4,
      4,
      2,
      3,
      4
    ]
  },
  {
    "id": "general-and-operations-managers",
    "title": {
      "en": "General and Operations Managers",
      "zh": "运营总经理"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      4,
      2,
      5,
      4,
      3,
      3,
      4,
      3,
      4,
      3,
      3,
      4,
      5,
      2,
      3,
      5
    ]
  },
  {
    "id": "sales-managers",
    "title": {
      "en": "Sales Managers",
      "zh": "销售经理"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      4,
      2,
      5,
      4,
      3,
      2,
      4,
      4,
      3,
      3,
      3,
      4,
      5,
      2,
      3,
      5
    ]
  },
  {
    "id": "medical-and-health-services-managers",
    "title": {
      "en": "Medical and Health Services Managers",
      "zh": "医疗服务经理"
    },
    "socGroup": 0,
    "archetype": "ESRH",
    "answers": [
      5,
      3,
      4,
      4,
      3,
      3,
      4,
      3,
      4,
      2,
      3,
      4,
      4,
      2,
      3,
      4
    ]
  },
  {
    "id": "financial-managers",
    "title": {
      "en": "Financial Managers",
      "zh": "财务经理"
    },
    "socGroup": 0,
    "archetype": "EORH",
    "answers": [
      5,
      4,
      4,
      3,
      4,
      3,
      4,
      3,
      4,
      2,
      2,
      4,
      4,
      2,
      2,
      4
    ]
  },
  {
    "id": "child-family-and-school-social-workers",
    "title": {
      "en": "Child, Family, and School Social Workers",
      "zh": "儿童与家庭社工"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      3,
      3,
      5,
      4,
      2,
      2,
      4,
      4,
      4,
      2,
      2,
      5,
      4,
      2,
      4,
      5
    ]
  },
  {
    "id": "police-and-sheriff-s-patrol-officers",
    "title": {
      "en": "Police and Sheriff's Patrol Officers",
      "zh": "警察与治安巡逻警"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      2,
      3,
      4,
      4,
      2,
      2,
      4,
      3,
      5,
      2,
      2,
      5,
      3,
      3,
      5,
      4
    ]
  },
  {
    "id": "detectives-and-criminal-investigators",
    "title": {
      "en": "Detectives and Criminal Investigators",
      "zh": "刑警与刑事调查员"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      3,
      3,
      4,
      4,
      2,
      2,
      4,
      3,
      5,
      2,
      2,
      5,
      3,
      3,
      4,
      4
    ]
  },
  {
    "id": "security-guards",
    "title": {
      "en": "Security Guards",
      "zh": "安保人员"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      2,
      4,
      3,
      3,
      3,
      3,
      3,
      2,
      4,
      3,
      3,
      4,
      2,
      4,
      5,
      3
    ]
  },
  {
    "id": "first-line-supervisors-of-police-and-det",
    "title": {
      "en": "First-Line Supervisors of Police and Detectives",
      "zh": "警察一线主管"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      3,
      3,
      4,
      4,
      2,
      2,
      4,
      3,
      5,
      2,
      2,
      5,
      3,
      3,
      5,
      4
    ]
  },
  {
    "id": "correctional-officers-and-jailers",
    "title": {
      "en": "Correctional Officers and Jailers",
      "zh": "狱警"
    },
    "socGroup": 0,
    "archetype": "TORP",
    "answers": [
      2,
      3,
      4,
      3,
      3,
      3,
      3,
      2,
      4,
      2,
      3,
      4,
      2,
      4,
      5,
      3
    ]
  },
  {
    "id": "firefighters",
    "title": {
      "en": "Firefighters",
      "zh": "消防员"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      2,
      3,
      4,
      4,
      2,
      2,
      4,
      3,
      5,
      2,
      2,
      5,
      3,
      3,
      5,
      4
    ]
  },
  {
    "id": "chief-executives",
    "title": {
      "en": "Chief Executives",
      "zh": "首席执行官"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      4,
      2,
      5,
      4,
      3,
      2,
      5,
      4,
      4,
      3,
      3,
      4,
      5,
      2,
      3,
      5
    ]
  },
  {
    "id": "marketing-managers",
    "title": {
      "en": "Marketing Managers",
      "zh": "市场营销经理"
    },
    "socGroup": 0,
    "archetype": "ESFH",
    "answers": [
      5,
      3,
      4,
      4,
      3,
      2,
      5,
      4,
      3,
      3,
      4,
      3,
      4,
      2,
      2,
      4
    ]
  },
  {
    "id": "human-resources-managers",
    "title": {
      "en": "Human Resources Managers",
      "zh": "人力资源经理"
    },
    "socGroup": 0,
    "archetype": "ESRH",
    "answers": [
      5,
      3,
      4,
      3,
      3,
      3,
      4,
      3,
      3,
      3,
      3,
      4,
      4,
      2,
      3,
      4
    ]
  },
  {
    "id": "construction-managers",
    "title": {
      "en": "Construction Managers",
      "zh": "建筑项目经理"
    },
    "socGroup": 0,
    "archetype": "TORH",
    "answers": [
      3,
      3,
      4,
      3,
      4,
      3,
      4,
      3,
      4,
      3,
      3,
      4,
      4,
      2,
      4,
      3
    ]
  },
  {
    "id": "architectural-and-engineering-managers",
    "title": {
      "en": "Architectural and Engineering Managers",
      "zh": "建筑与工程经理"
    },
    "socGroup": 0,
    "archetype": "EORH",
    "answers": [
      5,
      3,
      4,
      4,
      4,
      3,
      4,
      3,
      4,
      3,
      3,
      4,
      4,
      2,
      3,
      3
    ]
  },
  {
    "id": "financial-analysts",
    "title": {
      "en": "Financial Analysts",
      "zh": "金融分析师"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      3,
      3,
      5,
      3,
      3,
      2,
      3,
      4,
      4,
      2,
      3,
      3,
      1,
      2
    ]
  },
  {
    "id": "personal-financial-advisors",
    "title": {
      "en": "Personal Financial Advisors",
      "zh": "理财顾问"
    },
    "socGroup": 0,
    "archetype": "EOFH",
    "answers": [
      5,
      4,
      3,
      3,
      4,
      3,
      3,
      3,
      3,
      4,
      3,
      3,
      5,
      2,
      2,
      4
    ]
  },
  {
    "id": "loan-officers",
    "title": {
      "en": "Loan Officers",
      "zh": "信贷专员"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      2,
      2,
      5,
      4,
      2,
      2,
      3,
      3,
      3,
      3,
      4,
      3,
      2,
      3
    ]
  },
  {
    "id": "compliance-officers",
    "title": {
      "en": "Compliance Officers",
      "zh": "合规官"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      5,
      4,
      3,
      2,
      5,
      4,
      2,
      2,
      4,
      2,
      2,
      4,
      3,
      3,
      2,
      3
    ]
  },
  {
    "id": "logisticians",
    "title": {
      "en": "Logisticians",
      "zh": "物流分析师"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      2,
      2,
      5,
      4,
      3,
      2,
      3,
      4,
      4,
      2,
      3,
      3,
      2,
      2
    ]
  },
  {
    "id": "web-developers",
    "title": {
      "en": "Web Developers",
      "zh": "网页开发工程师"
    },
    "socGroup": 0,
    "archetype": "ESFP",
    "answers": [
      5,
      4,
      3,
      3,
      4,
      2,
      4,
      4,
      2,
      5,
      4,
      2,
      2,
      4,
      1,
      2
    ]
  },
  {
    "id": "computer-programmers",
    "title": {
      "en": "Computer Programmers",
      "zh": "计算机程序员"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      3,
      3,
      4,
      3,
      4,
      3,
      3,
      4,
      4,
      2,
      2,
      4,
      1,
      2
    ]
  },
  {
    "id": "information-security-analysts",
    "title": {
      "en": "Information Security Analysts",
      "zh": "信息安全分析师"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      5,
      4,
      3,
      3,
      4,
      3,
      4,
      2,
      4,
      3,
      3,
      3,
      2,
      3,
      2,
      2
    ]
  },
  {
    "id": "database-administrators",
    "title": {
      "en": "Database Administrators",
      "zh": "数据库管理员"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      3,
      2,
      5,
      4,
      3,
      2,
      3,
      4,
      4,
      2,
      2,
      4,
      1,
      2
    ]
  },
  {
    "id": "web-and-digital-interface-designers",
    "title": {
      "en": "Web and Digital Interface Designers",
      "zh": "网页与界面设计师"
    },
    "socGroup": 0,
    "archetype": "TSFP",
    "answers": [
      5,
      2,
      4,
      4,
      2,
      2,
      4,
      5,
      2,
      5,
      4,
      2,
      3,
      3,
      1,
      3
    ]
  },
  {
    "id": "aerospace-engineers",
    "title": {
      "en": "Aerospace Engineers",
      "zh": "航空航天工程师"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      5,
      4,
      4,
      4,
      4,
      3,
      4,
      3,
      5,
      2,
      2,
      3,
      2,
      3,
      3,
      3
    ]
  },
  {
    "id": "chemical-engineers",
    "title": {
      "en": "Chemical Engineers",
      "zh": "化学工程师"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      5,
      4,
      4,
      3,
      4,
      3,
      4,
      3,
      5,
      2,
      2,
      3,
      2,
      3,
      3,
      3
    ]
  },
  {
    "id": "surveyors",
    "title": {
      "en": "Surveyors",
      "zh": "测量员"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      3,
      4,
      3,
      2,
      5,
      4,
      3,
      2,
      4,
      3,
      3,
      3,
      3,
      3,
      4,
      2
    ]
  },
  {
    "id": "chemists",
    "title": {
      "en": "Chemists",
      "zh": "化学家"
    },
    "socGroup": 0,
    "archetype": "ESFH",
    "answers": [
      5,
      3,
      4,
      4,
      4,
      2,
      4,
      3,
      4,
      4,
      3,
      3,
      3,
      2,
      3,
      3
    ]
  },
  {
    "id": "biological-scientists",
    "title": {
      "en": "Biological Scientists",
      "zh": "生物科学家"
    },
    "socGroup": 0,
    "archetype": "TSFH",
    "answers": [
      5,
      3,
      4,
      5,
      4,
      2,
      4,
      3,
      4,
      4,
      3,
      3,
      3,
      2,
      3,
      3
    ]
  },
  {
    "id": "economists",
    "title": {
      "en": "Economists",
      "zh": "经济学家"
    },
    "socGroup": 0,
    "archetype": "ESFP",
    "answers": [
      5,
      4,
      3,
      4,
      4,
      2,
      4,
      3,
      3,
      4,
      4,
      3,
      3,
      2,
      1,
      3
    ]
  },
  {
    "id": "statisticians",
    "title": {
      "en": "Statisticians",
      "zh": "统计学家"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      3,
      3,
      5,
      3,
      4,
      2,
      3,
      4,
      4,
      2,
      2,
      3,
      1,
      2
    ]
  },
  {
    "id": "urban-and-regional-planners",
    "title": {
      "en": "Urban and Regional Planners",
      "zh": "城市规划师"
    },
    "socGroup": 0,
    "archetype": "ESRH",
    "answers": [
      5,
      3,
      4,
      4,
      3,
      2,
      4,
      4,
      4,
      3,
      3,
      4,
      3,
      2,
      3,
      3
    ]
  },
  {
    "id": "psychologists",
    "title": {
      "en": "Psychologists",
      "zh": "心理学家"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      4,
      3,
      5,
      4,
      2,
      1,
      5,
      4,
      4,
      3,
      2,
      5,
      5,
      2,
      4,
      5
    ]
  },
  {
    "id": "substance-abuse-and-mental-health-counse",
    "title": {
      "en": "Substance Abuse and Mental Health Counselors",
      "zh": "心理健康咨询师"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      3,
      3,
      5,
      4,
      1,
      1,
      5,
      4,
      4,
      3,
      2,
      5,
      5,
      2,
      4,
      5
    ]
  },
  {
    "id": "clergy",
    "title": {
      "en": "Clergy",
      "zh": "神职人员"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      2,
      2,
      5,
      4,
      1,
      1,
      5,
      5,
      3,
      3,
      2,
      5,
      5,
      1,
      4,
      5
    ]
  },
  {
    "id": "librarians-and-media-collections-special",
    "title": {
      "en": "Librarians and Media Collections Specialists",
      "zh": "图书馆员"
    },
    "socGroup": 0,
    "archetype": "ESFP",
    "answers": [
      5,
      4,
      3,
      2,
      3,
      3,
      4,
      3,
      2,
      4,
      4,
      3,
      3,
      3,
      3,
      3
    ]
  },
  {
    "id": "teaching-assistants",
    "title": {
      "en": "Teaching Assistants",
      "zh": "助教"
    },
    "socGroup": 0,
    "archetype": "ESFH",
    "answers": [
      3,
      4,
      3,
      2,
      3,
      3,
      4,
      3,
      2,
      4,
      4,
      3,
      3,
      4,
      5,
      3
    ]
  },
  {
    "id": "writers-and-authors",
    "title": {
      "en": "Writers and Authors",
      "zh": "作家"
    },
    "socGroup": 0,
    "archetype": "TSFH",
    "answers": [
      5,
      2,
      5,
      5,
      1,
      1,
      5,
      5,
      2,
      5,
      4,
      3,
      4,
      2,
      1,
      4
    ]
  },
  {
    "id": "news-reporters-and-journalists",
    "title": {
      "en": "News Reporters and Journalists",
      "zh": "记者"
    },
    "socGroup": 0,
    "archetype": "ESRH",
    "answers": [
      5,
      3,
      4,
      4,
      2,
      2,
      4,
      4,
      3,
      3,
      3,
      4,
      3,
      3,
      3,
      4
    ]
  },
  {
    "id": "photographers",
    "title": {
      "en": "Photographers",
      "zh": "摄影师"
    },
    "socGroup": 0,
    "archetype": "TSFH",
    "answers": [
      3,
      2,
      5,
      4,
      2,
      1,
      5,
      5,
      2,
      4,
      4,
      3,
      4,
      3,
      4,
      4
    ]
  },
  {
    "id": "musicians-and-singers",
    "title": {
      "en": "Musicians and Singers",
      "zh": "音乐家与歌手"
    },
    "socGroup": 0,
    "archetype": "TSFH",
    "answers": [
      2,
      2,
      5,
      4,
      1,
      1,
      5,
      5,
      2,
      4,
      4,
      4,
      5,
      2,
      5,
      5
    ]
  },
  {
    "id": "actors",
    "title": {
      "en": "Actors",
      "zh": "演员"
    },
    "socGroup": 0,
    "archetype": "TSFH",
    "answers": [
      2,
      2,
      5,
      4,
      1,
      1,
      5,
      5,
      2,
      4,
      4,
      4,
      4,
      3,
      5,
      5
    ]
  },
  {
    "id": "fashion-designers",
    "title": {
      "en": "Fashion Designers",
      "zh": "时装设计师"
    },
    "socGroup": 0,
    "archetype": "TSFP",
    "answers": [
      5,
      2,
      5,
      4,
      2,
      1,
      5,
      5,
      2,
      5,
      4,
      3,
      4,
      3,
      2,
      3
    ]
  },
  {
    "id": "film-and-video-editors",
    "title": {
      "en": "Film and Video Editors",
      "zh": "影视剪辑师"
    },
    "socGroup": 0,
    "archetype": "TSFP",
    "answers": [
      5,
      2,
      4,
      4,
      2,
      2,
      4,
      5,
      2,
      5,
      4,
      2,
      3,
      3,
      1,
      3
    ]
  },
  {
    "id": "physicians-and-surgeons",
    "title": {
      "en": "Physicians and Surgeons",
      "zh": "医生与外科医生"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      3,
      4,
      5,
      4,
      3,
      2,
      4,
      3,
      5,
      1,
      1,
      5,
      4,
      2,
      5,
      5
    ]
  },
  {
    "id": "dentists",
    "title": {
      "en": "Dentists",
      "zh": "牙医"
    },
    "socGroup": 0,
    "archetype": "TORH",
    "answers": [
      3,
      4,
      5,
      3,
      4,
      3,
      3,
      3,
      5,
      1,
      2,
      5,
      4,
      2,
      5,
      5
    ]
  },
  {
    "id": "pharmacists",
    "title": {
      "en": "Pharmacists",
      "zh": "药剂师"
    },
    "socGroup": 0,
    "archetype": "EORH",
    "answers": [
      4,
      5,
      3,
      2,
      5,
      5,
      2,
      1,
      5,
      2,
      1,
      5,
      3,
      3,
      4,
      4
    ]
  },
  {
    "id": "physician-assistants",
    "title": {
      "en": "Physician Assistants",
      "zh": "医师助理"
    },
    "socGroup": 0,
    "archetype": "EORH",
    "answers": [
      3,
      4,
      4,
      3,
      4,
      3,
      3,
      2,
      5,
      2,
      2,
      5,
      3,
      3,
      5,
      4
    ]
  },
  {
    "id": "physical-therapists",
    "title": {
      "en": "Physical Therapists",
      "zh": "物理治疗师"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      3,
      4,
      5,
      3,
      3,
      2,
      4,
      3,
      4,
      3,
      2,
      5,
      4,
      2,
      5,
      5
    ]
  },
  {
    "id": "occupational-therapists",
    "title": {
      "en": "Occupational Therapists",
      "zh": "职业治疗师"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      3,
      4,
      5,
      3,
      3,
      2,
      4,
      3,
      4,
      3,
      2,
      5,
      4,
      2,
      5,
      5
    ]
  },
  {
    "id": "speech-language-pathologists",
    "title": {
      "en": "Speech-Language Pathologists",
      "zh": "言语病理师"
    },
    "socGroup": 0,
    "archetype": "ESRH",
    "answers": [
      4,
      4,
      4,
      3,
      3,
      2,
      4,
      3,
      4,
      3,
      2,
      4,
      4,
      2,
      4,
      5
    ]
  },
  {
    "id": "veterinarians",
    "title": {
      "en": "Veterinarians",
      "zh": "兽医"
    },
    "socGroup": 0,
    "archetype": "TORH",
    "answers": [
      3,
      4,
      5,
      3,
      4,
      3,
      3,
      3,
      5,
      2,
      2,
      4,
      4,
      2,
      5,
      4
    ]
  },
  {
    "id": "dental-hygienists",
    "title": {
      "en": "Dental Hygienists",
      "zh": "口腔卫生师"
    },
    "socGroup": 0,
    "archetype": "EORH",
    "answers": [
      3,
      4,
      4,
      2,
      4,
      4,
      3,
      2,
      4,
      2,
      3,
      4,
      3,
      3,
      5,
      4
    ]
  },
  {
    "id": "dietitians-and-nutritionists",
    "title": {
      "en": "Dietitians and Nutritionists",
      "zh": "营养师"
    },
    "socGroup": 0,
    "archetype": "ESRH",
    "answers": [
      4,
      4,
      4,
      3,
      3,
      2,
      4,
      3,
      3,
      3,
      3,
      4,
      4,
      3,
      4,
      4
    ]
  },
  {
    "id": "radiologic-technologists",
    "title": {
      "en": "Radiologic Technologists",
      "zh": "放射技师"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      4,
      4,
      3,
      2,
      5,
      4,
      3,
      2,
      4,
      2,
      3,
      4,
      2,
      4,
      5,
      3
    ]
  },
  {
    "id": "emergency-medical-technicians-and-parame",
    "title": {
      "en": "Emergency Medical Technicians and Paramedics",
      "zh": "急救医护员"
    },
    "socGroup": 0,
    "archetype": "TORH",
    "answers": [
      2,
      4,
      4,
      3,
      3,
      3,
      3,
      2,
      5,
      2,
      2,
      4,
      3,
      3,
      5,
      4
    ]
  },
  {
    "id": "dental-assistants",
    "title": {
      "en": "Dental Assistants",
      "zh": "牙科助理"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      3,
      4,
      3,
      2,
      4,
      4,
      3,
      2,
      4,
      3,
      3,
      4,
      2,
      4,
      5,
      3
    ]
  },
  {
    "id": "home-health-and-personal-care-aides",
    "title": {
      "en": "Home Health and Personal Care Aides",
      "zh": "居家护理员"
    },
    "socGroup": 0,
    "archetype": "TSRH",
    "answers": [
      1,
      3,
      4,
      3,
      2,
      3,
      3,
      3,
      4,
      3,
      3,
      4,
      3,
      4,
      5,
      4
    ]
  },
  {
    "id": "massage-therapists",
    "title": {
      "en": "Massage Therapists",
      "zh": "按摩治疗师"
    },
    "socGroup": 0,
    "archetype": "TSFH",
    "answers": [
      1,
      3,
      5,
      2,
      2,
      2,
      3,
      4,
      3,
      4,
      4,
      3,
      5,
      3,
      5,
      4
    ]
  },
  {
    "id": "real-estate-sales-agents",
    "title": {
      "en": "Real Estate Sales Agents",
      "zh": "房地产经纪人"
    },
    "socGroup": 0,
    "archetype": "ESFH",
    "answers": [
      4,
      3,
      4,
      3,
      3,
      2,
      4,
      3,
      3,
      4,
      3,
      3,
      5,
      2,
      3,
      4
    ]
  },
  {
    "id": "sales-engineers",
    "title": {
      "en": "Sales Engineers",
      "zh": "销售工程师"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      4,
      3,
      4,
      3,
      3,
      3,
      3,
      4,
      3,
      3,
      4,
      3,
      2,
      3
    ]
  },
  {
    "id": "securities-and-financial-services-sales-",
    "title": {
      "en": "Securities and Financial Services Sales Agents",
      "zh": "证券经纪人"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      3,
      3,
      4,
      3,
      3,
      2,
      3,
      4,
      3,
      3,
      4,
      3,
      1,
      3
    ]
  },
  {
    "id": "travel-agents",
    "title": {
      "en": "Travel Agents",
      "zh": "旅行顾问"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      5,
      4,
      2,
      2,
      4,
      4,
      2,
      2,
      2,
      4,
      4,
      2,
      4,
      4,
      2,
      3
    ]
  },
  {
    "id": "automotive-service-technicians-and-mecha",
    "title": {
      "en": "Automotive Service Technicians and Mechanics",
      "zh": "汽车维修技师"
    },
    "socGroup": 0,
    "archetype": "TOFP",
    "answers": [
      2,
      3,
      4,
      3,
      4,
      4,
      2,
      2,
      4,
      4,
      3,
      3,
      3,
      4,
      5,
      2
    ]
  },
  {
    "id": "heating-air-conditioning-and-refrigerati",
    "title": {
      "en": "Heating, Air Conditioning, and Refrigeration Mechanics",
      "zh": "暖通空调技工"
    },
    "socGroup": 0,
    "archetype": "TORP",
    "answers": [
      2,
      3,
      4,
      3,
      4,
      4,
      2,
      2,
      4,
      3,
      3,
      3,
      3,
      4,
      5,
      2
    ]
  },
  {
    "id": "aircraft-mechanics-and-service-technicia",
    "title": {
      "en": "Aircraft Mechanics and Service Technicians",
      "zh": "飞机维修技师"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      3,
      4,
      4,
      3,
      5,
      4,
      2,
      2,
      5,
      2,
      2,
      4,
      2,
      4,
      5,
      2
    ]
  },
  {
    "id": "industrial-machinery-mechanics",
    "title": {
      "en": "Industrial Machinery Mechanics",
      "zh": "工业机械维修工"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      2,
      4,
      4,
      2,
      5,
      4,
      2,
      2,
      4,
      3,
      3,
      3,
      2,
      4,
      5,
      2
    ]
  },
  {
    "id": "airline-pilots-copilots-and-flight-engin",
    "title": {
      "en": "Airline Pilots, Copilots, and Flight Engineers",
      "zh": "飞行员"
    },
    "socGroup": 0,
    "archetype": "EORH",
    "answers": [
      4,
      4,
      4,
      3,
      5,
      4,
      2,
      2,
      5,
      1,
      2,
      4,
      2,
      3,
      5,
      3
    ]
  },
  {
    "id": "flight-attendants",
    "title": {
      "en": "Flight Attendants",
      "zh": "空乘人员"
    },
    "socGroup": 0,
    "archetype": "EORH",
    "answers": [
      2,
      4,
      2,
      2,
      3,
      4,
      3,
      2,
      4,
      3,
      3,
      3,
      3,
      4,
      5,
      3
    ]
  },
  {
    "id": "bus-drivers-transit-and-intercity",
    "title": {
      "en": "Bus Drivers, Transit and Intercity",
      "zh": "公交车司机"
    },
    "socGroup": 0,
    "archetype": "EORP",
    "answers": [
      2,
      4,
      2,
      2,
      4,
      4,
      2,
      1,
      4,
      3,
      3,
      3,
      2,
      4,
      5,
      2
    ]
  },
  {
    "id": "couriers-and-delivery-drivers",
    "title": {
      "en": "Couriers and Delivery Drivers",
      "zh": "快递配送员"
    },
    "socGroup": 0,
    "archetype": "EOFP",
    "answers": [
      3,
      4,
      2,
      1,
      4,
      4,
      2,
      1,
      3,
      4,
      4,
      2,
      2,
      5,
      5,
      2
    ]
  },
  {
    "id": "farmers-ranchers-and-agricultural-manage",
    "title": {
      "en": "Farmers, Ranchers, and Agricultural Managers",
      "zh": "农场主与农业经理"
    },
    "socGroup": 0,
    "archetype": "TOFH",
    "answers": [
      2,
      3,
      4,
      3,
      4,
      3,
      3,
      3,
      4,
      3,
      4,
      2,
      3,
      3,
      5,
      2
    ]
  },
  {
    "id": "chefs-and-head-cooks",
    "title": {
      "en": "Chefs and Head Cooks",
      "zh": "主厨"
    },
    "socGroup": 0,
    "archetype": "TSFH",
    "answers": [
      1,
      3,
      5,
      3,
      2,
      2,
      4,
      5,
      3,
      4,
      4,
      3,
      4,
      3,
      5,
      4
    ]
  }
];
